name 'puppet-tsmclient'
version '0.0.1'
author 'rdark'
license 'GPL-2.0'
summary 'Install and configure the Tivoli Storage Manager client.'
project_page 'https://github.com/rdark/puppet-tsmclient'
source 'https://github.com/rdark/puppet-tsmclient.git'
dependency 'example42/puppi', '>=2.0.0'
